import Head from "next/head";
import AppButton from "../components/AppButton";
import styles from "../styles/Home.module.css";

export default function Home() {
  const btnList: Array<any> = [{ id: 1 , begin : 10}, { id: 2 }, { id: 3 }, { id: 4 }];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Click Me</p>
      {btnList.map((btn) => {
        return <AppButton appButton={btn} key={btn.id}></AppButton>;
      })}
    </div>
  );
}
